var bingoList = [];
bingoList[1] = [
    {name: ".52 Gal", image: "../weapons/001.png"},
    {name: ".96 Gal", image: "../weapons/002.png"},
    {name: "Aerospray MG", image: "../weapons/003.png"},
    {name: "Ballpoint Splatling", image: "../weapons/004.png"},
    {name: "Bamboozler 14 Mk I", image: "../weapons/005.png"},
    {name: "Blaster", image: "../weapons/006.png"},
    {name: "Bloblobber", image: "../weapons/007.png"},
    {name: "Carbon Roller", image: "../weapons/008.png"},
    {name: "Clash Blaster", image: "../weapons/009.png"},
    {name: "Squiffer", image: "../weapons/010.png"},
    {name: "Dapple Dualies", image: "../weapons/011.png"},
    {name: "Dark Tetra Dualies", image: "../weapons/012.png"},
    {name: "Dualie Squelchers", image: "../weapons/013.png"},
    {name: "Dynamo Roller", image: "../weapons/014.png"},
    {name: "E-liter 4K", image: "../weapons/015.png"},
    {name: "E-liter 4K Scope", image: "../weapons/016.png"},
    {name: "Explosher", image: "../weapons/017.png"},
    {name: "Flingza Roller", image: "../weapons/018.png"},
    {name: "Glooga Dualies", image: "../weapons/019.png"},
    {name: "Goo Tuber", image: "../weapons/020.png"},
    {name: "H-3 Nozzlenose", image: "../weapons/021.png"},
    {name: "Heavy Splatling", image: "../weapons/022.png"},
    {name: "Hero Shot Replica", image: "../weapons/023.png"},
    {name: "Hydra Splatling", image: "../weapons/024.png"},
    {name: "Inkbrush", image: "../weapons/025.png"},
    {name: "Jet Squelcher", image: "../weapons/026.png"},
    {name: "L-3 Nozzlenose", image: "../weapons/027.png"},
    {name: "Luna Blaster", image: "../weapons/028.png"},
    {name: "Mini Splatling", image: "../weapons/029.png"},
    {name: "N-ZAP '85", image: "../weapons/030.png"},
    {name: "Nautilus 47", image: "../weapons/031.png"},
    {name: "Octobrush", image: "../weapons/032.png"},
    {name: "Range Blaster", image: "../weapons/033.png"},
    {name: "Rapid Blaster", image: "../weapons/034.png"},
    {name: "Rapid Blaster Pro", image: "../weapons/035.png"},
    {name: "REEF-LUX 450", image: "../weapons/036.png"},
    {name: "Slosher", image: "../weapons/037.png"},
    {name: "Sloshing Machine", image: "../weapons/038.png"},
    {name: "Splash-o-matic", image: "../weapons/039.png"},
    {name: "Splat Brella", image: "../weapons/040.png"},
    {name: "Splat Charger", image: "../weapons/041.png"},
    {name: "Splat Dualies", image: "../weapons/042.png"},
    {name: "Splat Roller", image: "../weapons/043.png"},
    {name: "Splatana Stamper", image: "../weapons/044.png"},
    {name: "Splatana Wiper", image: "../weapons/045.png"},
    {name: "Splatterscope", image: "../weapons/046.png"},
    {name: "Splattershot", image: "../weapons/047.png"},
    {name: "Splattershot Jr.", image: "../weapons/048.png"},
    {name: "Splattershot Pro", image: "../weapons/049.png"},
    {name: "Sploosh-o-matic", image: "../weapons/050.png"},
    {name: "Squeezer", image: "../weapons/051.png"},
    {name: "Tenta Brella", image: "../weapons/052.png"},
    {name: "Tri-Slosher", image: "../weapons/053.png"},
    {name: "Tri-Stringer", image: "../weapons/054.png"},
    {name: "Undercover Brella", image: "../weapons/055.png"}
];

$(function() { srl.bingo(bingoList, 5, false); });